workflows:
  android-debug:
    name: Hisab Ledger - Debug APK
    environment:
      java: 17
    scripts:
      - name: Build debug APK
        script: gradle --no-daemon --stacktrace assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk

  android-release:
    name: Hisab Ledger - Release APK
    environment:
      java: 17
    scripts:
      - name: Build release APK
        script: gradle --no-daemon --stacktrace assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
